version: 0.2

env:
    shell: bash

phases:
    pre_build:
        on-failure: ABORT
        commands:
            - antora --version
    build:
        commands:
            - antora --fetch antora-playbook.yml
artifacts:
    files:
        - 'build/*'
